config/routes.rb
Rails.application.routes.draw do
  # get 'reviews/index'
  # get 'reviews/new'
  # get 'reviews/create'
  # get 'restaurants/index'
  # get 'restaurants/show'
  # get 'restaurants/new'
  # get 'restaurants/create'

  resources :restaurants, only: [:index, :show, :new, :create] do
    resources :reviews, only: [:index, :new, :create]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, :address, :category, presence: true
  validates :category, inclusion: { in: ['chinese', 'italian', 'japanese', 'french', 'belgian'] }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, :rating, presence: true
  validates :rating, inclusion: { in: [0, 1, 2, 3, 4, 5] }
  validates :rating, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @reviews = @restaurant.reviews
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.save
    redirect_to restaurants_path
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :category, :phone_number)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_restaurant, only: [:index, :new]

  def index
    @reviews = @restaurant.reviews
  end

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_reviews_path(@restaurant)
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating, :restaurant_id)
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "Restaurants", restaurants_path, class: "navbar-brand"%>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <!-- <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a> -->
        <%= link_to "Create a restaurant", new_restaurant_path, class: "nav-link"%>
      </li>
    </ul>
  </div>
</nav>

    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for [@restaurant] do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :category %>
  <%= f.input :phone_number %>

  <%= f.submit "add a restaurant", class: "btn btn-primary" %>
<% end %>

app/views/restaurants/create.html.erb
<h1>Restaurants#create</h1>
<p>Find me in app/views/restaurants/create.html.erb</p>

app/views/restaurants/index.html.erb
<h1>Restaurants</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Address</th>
      <th scope="col">Phone Number</th>
      <th scope="col">Category</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
<% @restaurants.each do |restaurant| %>
    <tr>
      <th scope="row"><%= restaurant.id %></th>
      <td><%= restaurant.name %></td>
      <td><%= restaurant.address %></td>
      <td><%= restaurant.phone_number %></td>
      <td><%= restaurant.category %></td>
      <td>
        <%= link_to "Show restaurant", restaurant_path(restaurant.id) %>
        <%= link_to "Add review", new_restaurant_review_path(restaurant.id) %>
      </td>
    </tr>
<% end %>
</tbody>
</table>

app/views/restaurants/new.html.erb
<%= render 'form', restaurant: @restaurant %>

app/views/restaurants/show.html.erb
<div class="d-flex flex-column text-center">

<h1>Reviews for: <%= @restaurant.name %></h1>
<% @reviews.each do |review| %>
  <div class="align-self-center p-2 border w-25 m-3">
    <p>Stars: <%= review.rating %></p>
    <p><%= review.content %></p>
  </div>
<% end %>

</div>

app/views/reviews/_form.html.erb
<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :rating %>
  <%= f.input :content %>
  <%= f.submit "add a review", class: "btn btn-primary" %>
<% end %>

app/views/reviews/index.html.erb
<h2><%= @restaurant.name %>e</h2>
<% @reviews.each do |review| %>
  <h3><%= review[:rating] %></h3>
  <p><%= review[:content] %></p>
<% end %>

app/views/reviews/new.html.erb
<%= render 'form', restaurant: @restaurant, review: @review  %>